version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '06:00'
      timezone: Africa/Johannesburg
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - jon-nona
    rebase-strategy: disabled
