orbs:
  node: circleci/node@3.0.1
version: 2.1

jobs:
  test-build-deploy:
    executor:
      name: node/default
      tag: '12.18.2'
    steps:
      - checkout
      - node/install-packages:
          cache-version: v2
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run _test:ci
      - run:
          name: Build
          command: npm run build
      - when:
          condition:
            or:
              - equal: [develop, << pipeline.git.branch >>]
              - equal: [master, << pipeline.git.branch >>]
          steps:
            - add_ssh_keys:
                fingerprints:
                  - '88:9b:81:a0:b9:7c:16:77:97:88:ce:e0:9d:2a:de:f8'
            - run:
                name: Git setup
                command: git config --global user.email "jon@nonacreative.com" && git config --global user.name "jon-nona"
            - deploy:
                name: Publish package
                command: PACKAGE_TAG=v0.0.${CIRCLE_BUILD_NUM} npm run publish

workflows:
  test-build-deploy:
    jobs:
      - test-build-deploy
